<?php
/**
 * Titles and alt text for the prepared photographs.
 *
 * Generated by .ftp-sync/tools/prepare-photos.php from .ftp-sync/content/photos.json.
 * Edit the JSON and re-run the tool; do not edit this file.
 *
 * @package moderno-child
 */

return array (
  'omc-hero-black-midi-skirt' => 
  array (
    'title' => 'Black double-breasted coat on a city street',
    'alt' => 'Woman in a long black double-breasted coat walking a city street',
  ),
  'omc-hero-white-dress' => 
  array (
    'title' => 'Camel knit midi dress on a cobbled street',
    'alt' => 'Woman in a camel knit midi dress carrying a tan bag on a cobbled street',
  ),
  'omc-hero-pleated-skirt-light' => 
  array (
    'title' => 'Black button-front midi dress outside a boutique',
    'alt' => 'Woman in a black button-front midi dress walking past a boutique window',
  ),
  'omc-edit-collar-sweatshirt' => 
  array (
    'title' => 'Check midi skirt at a cafe window',
    'alt' => 'Woman in a brown check midi skirt and knit standing by a cafe window',
  ),
  'omc-edit-green-knit' => 
  array (
    'title' => 'Striped cardigan and cream skirt indoors',
    'alt' => 'Woman in a black and cream striped cardigan over a cream skirt',
  ),
  'omc-story-black-coat' => 
  array (
    'title' => 'Pink striped cardigan in a cafe',
    'alt' => 'Woman in a pink striped cardigan and pleated skirt seated in a cafe',
  ),
  'omc-newsletter-blue-skirt' => 
  array (
    'title' => 'Knit cardigan and pink pleated skirt at home',
    'alt' => 'Woman in a knit cardigan and pink pleated skirt seated on a cream sofa',
  ),
  'omc-live-plaid-shacket' => 
  array (
    'title' => 'Grey sweatshirt and a morning cup',
    'alt' => 'Woman in a grey sweatshirt holding a mug on a sofa',
  ),
  'omc-quotes-green-knit-sofa' => 
  array (
    'title' => 'Black midi dress by a hotel window',
    'alt' => 'Woman in a black midi dress standing by a floor-to-ceiling hotel window',
  ),
  'omc-about-plaid-street' => 
  array (
    'title' => 'Red trench coat in an autumn park',
    'alt' => 'Woman in a red belted trench coat walking through an autumn park',
  ),
  'omc-tile-new-in' => 
  array (
    'title' => 'Blue tiered midi skirt in motion',
    'alt' => 'Woman turning in a blue tiered midi skirt on a cobbled street',
  ),
  'omc-tile-knitwear' => 
  array (
    'title' => 'Fair Isle knit cardigan in winter light',
    'alt' => 'Woman in a cream Fair Isle knit cardigan holding a mug by a snowy window',
  ),
  'omc-tile-skirts' => 
  array (
    'title' => 'Striped pleated midi skirt on a street',
    'alt' => 'Woman in a striped pleated midi skirt and boots walking a shopping street',
  ),
  'omc-tile-dresses' => 
  array (
    'title' => 'Black midi dress on a city street',
    'alt' => 'Woman in a black midi dress and coat walking a city street',
  ),
  'omc-tile-outerwear' => 
  array (
    'title' => 'Check shacket worn open over a white tee',
    'alt' => 'Woman wearing an open pink check shacket over a white tee and jeans',
  ),
  'omc-tile-trousers' => 
  array (
    'title' => 'Fringed pleated skirt and white tee',
    'alt' => 'Woman in a fringed pleated midi skirt and white tee on a cobbled street',
  ),
  'omc-tile-occasion' => 
  array (
    'title' => 'Linen skirt and camisole at golden hour',
    'alt' => 'Woman in a linen midi skirt and camisole on a terrace at golden hour',
  ),
  'omc-carousel-colour' => 
  array (
    'title' => 'Skater skirt in black, red and blue',
    'alt' => 'Three skater skirts on a rail in black, red and blue',
  ),
  'omc-carousel-sweats' => 
  array (
    'title' => 'Sweatshirts in five colours',
    'alt' => 'Stack of crew-neck sweatshirts in black, white, lilac, coral and olive',
  ),
  'omc-carousel-trousers' => 
  array (
    'title' => 'Wide-leg knit trousers in four colours',
    'alt' => 'Four pairs of wide-leg knit trousers hanging in cream, grey, taupe and black',
  ),
  'omc-carousel-furvest' => 
  array (
    'title' => 'Faux fur gilet in silver grey',
    'alt' => 'A pair of silver grey faux fur gilets photographed flat',
  ),
  'omc-carousel-dresses' => 
  array (
    'title' => 'Shirt dress in five colourways',
    'alt' => 'Five shirt dresses side by side in cream, black, taupe and grey',
  ),
  'omc-carousel-coat' => 
  array (
    'title' => 'Cream wool blend coat',
    'alt' => 'A cream wool blend coat photographed flat on a white ground',
  ),
  'omc-carousel-plaid' => 
  array (
    'title' => 'Blue check overshirt worn open',
    'alt' => 'Woman wearing an oversized blue check overshirt over a white tee',
  ),
  'omc-carousel-beauty' => 
  array (
    'title' => 'Cica ampoule sheet mask',
    'alt' => 'A Cica ampoule sheet mask sachet from the Korean skincare shelf',
  ),
  'omc-carousel-bearvest' => 
  array (
    'title' => 'Bear motif knit vest in cream and grey',
    'alt' => 'Two bear motif knit vests on hangers, one cream and one grey',
  ),
  'omc-banner-seoul-1' => 
  array (
    'title' => 'Black pleated midi skirt on a cobbled street',
    'alt' => 'Woman in a black pleated midi skirt and cream knit on a cobbled street',
  ),
  'omc-banner-seoul-2' => 
  array (
    'title' => 'Cream pleated skirt in window light',
    'alt' => 'Woman in a cream pleated midi skirt and fine knit at a bright window',
  ),
  'omc-banner-seoul-3' => 
  array (
    'title' => 'Embroidered knit vest over a blouse',
    'alt' => 'Woman in an embroidered knit vest layered over a cream blouse',
  ),
  'omc-banner-bangkok-1' => 
  array (
    'title' => 'Linen midi skirt on a terrace at golden hour',
    'alt' => 'Woman in a linen midi skirt and camisole on a terrace at golden hour',
  ),
  'omc-banner-bangkok-2' => 
  array (
    'title' => 'Striped top and grey midi skirt',
    'alt' => 'Woman in a striped top and grey midi skirt carrying a shoulder bag',
  ),
  'omc-banner-bangkok-3' => 
  array (
    'title' => 'Sage knit jumper among autumn trees',
    'alt' => 'Woman in a sage green oversized knit jumper and jeans among autumn trees',
  ),
  'omc-cat-dresses' => 
  array (
    'title' => 'Black button-front midi dress',
    'alt' => 'Woman in a black button-front midi dress walking a city street',
  ),
  'omc-cat-skirts' => 
  array (
    'title' => 'Grey check pencil skirt in daylight',
    'alt' => 'Woman in a grey check pencil skirt and black knit in a bright room',
  ),
  'omc-cat-tops' => 
  array (
    'title' => 'Cream knit top on a sofa',
    'alt' => 'Woman in a cream knit top seated on a cream sofa',
  ),
  'omc-cat-knits' => 
  array (
    'title' => 'Black knit dress by a window',
    'alt' => 'Woman in a black fine-knit dress standing by a window',
  ),
  'omc-cat-trousers' => 
  array (
    'title' => 'Check tailored trousers in an office',
    'alt' => 'Woman in check tailored trousers and a cream blouse in an office',
  ),
  'omc-cat-jeans' => 
  array (
    'title' => 'Washed blue denim jeans',
    'alt' => 'A pair of washed blue denim jeans photographed from behind',
  ),
  'omc-cat-sets' => 
  array (
    'title' => 'Cream knit co-ord set',
    'alt' => 'Woman in a cream knit top and matching trousers on a sofa',
  ),
  'omc-journal-thai' => 
  array (
    'title' => 'Blue embroidered midi skirt in daylight',
    'alt' => 'Woman in a blue embroidered midi skirt standing in a bright room',
  ),
  'omc-journal-hanbok' => 
  array (
    'title' => 'Monochrome tweed dress with a shoulder bag',
    'alt' => 'Woman in a black and cream tweed dress holding a shoulder bag',
  ),
  'omc-journal-decades' => 
  array (
    'title' => 'Brown check midi skirt on cobbles',
    'alt' => 'Woman in a brown check midi skirt and boots walking a cobbled street',
  ),
  'omc-journal-kpop' => 
  array (
    'title' => 'Floral trim faux fur jacket outdoors',
    'alt' => 'Woman in a cream floral-trim faux fur jacket and jeans outdoors',
  ),
  'omc-journal-street' => 
  array (
    'title' => 'Grey midi skirt on an autumn street',
    'alt' => 'Woman in a grey midi skirt and knit walking an autumn street',
  ),
  'omc-journal-brands' => 
  array (
    'title' => 'A rail of knitwear and coats',
    'alt' => 'Woman beside a clothing rail of knitwear, coats and dresses',
  ),
  'omc-journal-kawaii' => 
  array (
    'title' => 'Pink faux fur jacket in window light',
    'alt' => 'Woman in a pink and cream faux fur jacket holding a cup by a window',
  ),
  'omc-journal-vacation' => 
  array (
    'title' => 'Quilted midi skirt at a pavement cafe',
    'alt' => 'Woman in a quilted brown midi skirt walking past a pavement cafe',
  ),
);
